# This file was generated by an automatic VDL release script. DO NOT EDIT.
class VdlNext < Formula
  desc "Open-source cross-language definition engine for modern stacks. Define your data structures, APIs, contracts, and generate type-safe code for your backend and frontend instantly."
  homepage "https://varavel.com/vdl"
  license "MIT"
  version "0.4.0-alpha.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/vdl/releases/download/v0.4.0-alpha.5/vdl_darwin_arm64.tar.gz"
      sha256 "cf953570bc3fe0df46759cfb6e8a866d54908bbca0ce2efaa54aa3e27190a607"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.4.0-alpha.5/vdl_darwin_amd64.tar.gz"
      sha256 "68460071258a1511a588c8b6a4a17bd5388734038b75fdfbd0f90ccdd1b27b2a"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/vdl/releases/download/v0.4.0-alpha.5/vdl_linux_arm64.tar.gz"
      sha256 "751397665f0f682c11981a121abd04bf28952fc0dc4a9d29e193db0f8baf0ced"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.4.0-alpha.5/vdl_linux_amd64.tar.gz"
      sha256 "994e35a6e27363cac2892a8290a9c8921b405616633829116b3d40ccb13bbb64"
    end
  end

  def install
    bin.install "vdl"
  end

  test do
    system "#{bin}/vdl", "version"
  end
end

