# This file was generated by an automatic VDL release script. DO NOT EDIT.
class VdlNext < Formula
  desc "Open-source cross-language definition engine for modern stacks. Define your data structures, APIs, contracts, and generate type-safe code for your backend and frontend instantly."
  homepage "https://varavel.com/vdl"
  license "MIT"
  version "0.5.0-alpha.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.4/vdl_darwin_arm64.tar.gz"
      sha256 "5ae2344f1b27a22be3d4e8a24c6eec9487e10dcc41400b34e78912e95cd4bad6"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.4/vdl_darwin_amd64.tar.gz"
      sha256 "a9ee8cb9f18cbe20f98a9306642fe77c3b79c343cd1d9cbb681cf13cfd9e3f22"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.4/vdl_linux_arm64.tar.gz"
      sha256 "81e58f3898b78e04a30caa4076c5260ebb1f04dc92764138e4d26741cdaecf37"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.4/vdl_linux_amd64.tar.gz"
      sha256 "9cb0f41770afbd371c1b299f7125fe57c05e996bacb8f92063e723522e0bd620"
    end
  end

  def install
    bin.install "vdl"
  end

  test do
    system "#{bin}/vdl", "version"
  end
end

