# This file was generated by an automatic VDL release script. DO NOT EDIT.
class VdlAT050Alpha6 < Formula
  desc "Open-source cross-language definition engine for modern stacks. Define your data structures, APIs, contracts, and generate type-safe code for your backend and frontend instantly."
  homepage "https://varavel.com/vdl"
  license "MIT"
  version "0.5.0-alpha.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.6/vdl_darwin_arm64.tar.gz"
      sha256 "c0e55b225f33b0a436053c68ce84a58c354a9169737a33bd80a77b77f8554e4b"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.6/vdl_darwin_amd64.tar.gz"
      sha256 "41f5beda03b1b5e9fb8b826bd33029bfa8365d0e05699aa4b6e9845a1b3a5b2d"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.6/vdl_linux_arm64.tar.gz"
      sha256 "1ace462de5211e59e9b4c25ead521293d1c3cfb0e62a405468bf92b42649dcb2"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.6/vdl_linux_amd64.tar.gz"
      sha256 "f247c2b37abbb1925b8325a834da4ec71011c6ba9c11a71f9d2c3914ff464042"
    end
  end

  def install
    bin.install "vdl"
  end

  test do
    system "#{bin}/vdl", "version"
  end
end

