# This file was generated by an automatic VDL release script. DO NOT EDIT.
class VdlAT050Alpha5 < Formula
  desc "Open-source cross-language definition engine for modern stacks. Define your data structures, APIs, contracts, and generate type-safe code for your backend and frontend instantly."
  homepage "https://varavel.com/vdl"
  license "MIT"
  version "0.5.0-alpha.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.5/vdl_darwin_arm64.tar.gz"
      sha256 "8919460d4f9cf4db75ee9bcb6f708db5fda9bcbed085fe0abf7250ea49a6e67a"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.5/vdl_darwin_amd64.tar.gz"
      sha256 "89912bafe6c468457124e2998997ff4503f2c92529f385ca455256104a17ad2b"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.5/vdl_linux_arm64.tar.gz"
      sha256 "a639ac4d9c3e294c4313da48e10e7c3156337940bdfd403d5de64b0ab0c9b503"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.5/vdl_linux_amd64.tar.gz"
      sha256 "5dc629f79c21983012af72bd4372d0127fe34f7572edb10fde783f1d45985dea"
    end
  end

  def install
    bin.install "vdl"
  end

  test do
    system "#{bin}/vdl", "version"
  end
end

