# This file was generated by an automatic VDL release script. DO NOT EDIT.
class VdlAT050Alpha2 < Formula
  desc "Open-source cross-language definition engine for modern stacks. Define your data structures, APIs, contracts, and generate type-safe code for your backend and frontend instantly."
  homepage "https://varavel.com/vdl"
  license "MIT"
  version "0.5.0-alpha.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.2/vdl_darwin_arm64.tar.gz"
      sha256 "bc67a02c7112462598ed64896edff07b52ab2550b5a8ae504694342a14204b1e"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.2/vdl_darwin_amd64.tar.gz"
      sha256 "0705b14ac34492bd9401cc8f2652f7127aa60f21b59d04ae0bb965c373faf6cd"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.2/vdl_linux_arm64.tar.gz"
      sha256 "3c17cc0d1e2c02988bae0db22a216e13cab489b6d81d56a63ea014424b518744"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.2/vdl_linux_amd64.tar.gz"
      sha256 "2b847e8d595d060b77d0de4e88f29cd37cdfdc1da5b022931e66954703990e16"
    end
  end

  def install
    bin.install "vdl"
  end

  test do
    system "#{bin}/vdl", "version"
  end
end

