# This file was generated by an automatic VDL release script. DO NOT EDIT.
class VdlAT050Alpha3 < Formula
  desc "Open-source cross-language definition engine for modern stacks. Define your data structures, APIs, contracts, and generate type-safe code for your backend and frontend instantly."
  homepage "https://varavel.com/vdl"
  license "MIT"
  version "0.5.0-alpha.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.3/vdl_darwin_arm64.tar.gz"
      sha256 "8acd4f2163938cc1baae02a7228b96227c4d98d4e47a4a45241e68d513795aa1"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.3/vdl_darwin_amd64.tar.gz"
      sha256 "e1f5ae97644000b4403333242d90af5721418574b3f7d2996b5d53e44bccef57"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.3/vdl_linux_arm64.tar.gz"
      sha256 "b9481174b27dfd055473b2be97f869e9c6da5106af6dba768fc2d71b3c635158"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.3/vdl_linux_amd64.tar.gz"
      sha256 "32d926c734630012c2c2777220b3134a85a820d95f458d93873bce439ffbf61d"
    end
  end

  def install
    bin.install "vdl"
  end

  test do
    system "#{bin}/vdl", "version"
  end
end

