# This file was generated by an automatic VDL release script. DO NOT EDIT.
class VdlAT050Alpha1 < Formula
  desc "Open-source cross-language definition engine for modern stacks. Define your data structures, APIs, contracts, and generate type-safe code for your backend and frontend instantly."
  homepage "https://varavel.com/vdl"
  license "MIT"
  version "0.5.0-alpha.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.1/vdl_darwin_arm64.tar.gz"
      sha256 "5d5ed746cd852910605cd5bb16160950726a9c020ae8ecbd48decbb021687458"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.1/vdl_darwin_amd64.tar.gz"
      sha256 "5c0faecdd16d4744c60dd14dcebaf719d09e1c28a573c077db759c5ce8238ebc"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.1/vdl_linux_arm64.tar.gz"
      sha256 "810e827a1419cbffc8d4cc5b0fb31c807dc7827f1df80344c0c09a3fc8316885"
    else
      url "https://github.com/varavelio/vdl/releases/download/v0.5.0-alpha.1/vdl_linux_amd64.tar.gz"
      sha256 "2667631d803faf5e45f6e5cacc40ddbc814ba567ca71428ab6f6ccab4ea2a749"
    end
  end

  def install
    bin.install "vdl"
  end

  test do
    system "#{bin}/vdl", "version"
  end
end

