# This file was generated by the Rienda release workflow. DO NOT EDIT.
class RiendaNext < Formula
  desc "Simple, declarative, multi-agent LLM harness"
  homepage "https://github.com/varavelio/rienda"
  license "MIT"
  version "0.1.0-alpha.15"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/rienda/releases/download/v0.1.0-alpha.15/rienda_darwin_arm64.tar.gz"
      sha256 "a04b42fe2b1facc2863891266961a8755e337a2595dd2744b2ffbcdb5655c77a"
    else
      url "https://github.com/varavelio/rienda/releases/download/v0.1.0-alpha.15/rienda_darwin_amd64.tar.gz"
      sha256 "02bf2468900b17afcc1f2d8abf15b2f5c748165caba8af43cbf5cebbab775d6e"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/rienda/releases/download/v0.1.0-alpha.15/rienda_linux_arm64.tar.gz"
      sha256 "ac086245f59a54d0b6cc2a79874e6f6b5abbdb0eb33d7e04de067bd19e8ab682"
    else
      url "https://github.com/varavelio/rienda/releases/download/v0.1.0-alpha.15/rienda_linux_amd64.tar.gz"
      sha256 "2dc36e608293748dee2a6d66679984fbeb6df22e28c01ab28ce50a8f362d8cf2"
    end
  end

  def install
    bin.install "rienda"
  end

  test do
    system "#{bin}/rienda", "--help"
  end
end
