# This file was generated by the Rienda release workflow. DO NOT EDIT.
class RiendaNext < Formula
  desc "Simple, declarative, multi-agent LLM harness"
  homepage "https://github.com/varavelio/rienda"
  license "MIT"
  version "0.1.0-alpha.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/rienda/releases/download/v0.1.0-alpha.3/rienda_darwin_arm64.tar.gz"
      sha256 "280f9730641677b18d025c0fe53576edac06b2dd6ed03d853e9faf9daa68ecb7"
    else
      url "https://github.com/varavelio/rienda/releases/download/v0.1.0-alpha.3/rienda_darwin_amd64.tar.gz"
      sha256 "edee8868f3437d3f64f45d05836535dfc491c432a7e84304cccfc189bb614f08"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/rienda/releases/download/v0.1.0-alpha.3/rienda_linux_arm64.tar.gz"
      sha256 "c0f5213cb4c4b9d3a140bd165152ad305c19f7bf8a5df853139a346ca0f38637"
    else
      url "https://github.com/varavelio/rienda/releases/download/v0.1.0-alpha.3/rienda_linux_amd64.tar.gz"
      sha256 "05df999b970a9ac12079c7517ca61c356478d787828c3809c12bb8d24f4f2b85"
    end
  end

  def install
    bin.install "rienda"
  end

  test do
    system "#{bin}/rienda", "--help"
  end
end
