# This file was generated by the Veta release workflow. DO NOT EDIT.
class VetaNext < Formula
  desc "Veta is the varavel's static site generator"
  homepage "https://github.com/varavelio/veta"
  license "MIT"
  version "0.1.0-alpha.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.1/veta_darwin_arm64.tar.gz"
      sha256 "ed6dc793396abdc8c6c1890bddcf3d4a58bbaf106dd4b52bd895f1bc9735ce37"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.1/veta_darwin_amd64.tar.gz"
      sha256 "c3b9e55f23fe42f672e861ec5c5c080c5c2600984e4333e0aec1d0253b854043"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.1/veta_linux_arm64.tar.gz"
      sha256 "e72b3d8e9d4533d4b58688e7ae22ba7a2ec37dd69fd5d888f8852bacab9ea7f0"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.1/veta_linux_amd64.tar.gz"
      sha256 "188e23680fe76d1f17d36dcad8c71ad21aaeb72af9be1cfff3e40877edfd0920"
    end
  end

  def install
    bin.install "veta"
  end

  test do
    system "#{bin}/veta", "--version"
  end
end
