# This file was generated by the Veta release workflow. DO NOT EDIT.
class VetaAT010 < Formula
  desc "Veta static site generator"
  homepage "https://github.com/varavelio/veta"
  license "MIT"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/veta/releases/download/v0.1.0/veta_darwin_arm64.tar.gz"
      sha256 "bc69faa1b59e7afc984bf44cded02b2d02b9119ba3a81e5e9b50a123f5d8ac89"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.0/veta_darwin_amd64.tar.gz"
      sha256 "8a29944c0b31d2dcc8ea104c54627b399f135f87c7e858e0084cf197400086d8"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/veta/releases/download/v0.1.0/veta_linux_arm64.tar.gz"
      sha256 "f6284cf3ea4d1ffd875ec7eef4cee673bdd860351778a02414dc01bc7d00b05c"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.0/veta_linux_amd64.tar.gz"
      sha256 "7b32afe9c19de116719a2b0a4787e7220916a3c82cd0284d76143af15c15d9a0"
    end
  end

  def install
    bin.install "veta"
  end

  test do
    system "#{bin}/veta", "--version"
  end
end
