# This file was generated by the Veta release workflow. DO NOT EDIT.
class VetaNext < Formula
  desc "Veta static site generator"
  homepage "https://github.com/varavelio/veta"
  license "MIT"
  version "0.1.0-alpha.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.4/veta_darwin_arm64.tar.gz"
      sha256 "98e3f9c82297fd1526dba0e027608b3e22811a1c9333fa636bccae9662ddcb32"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.4/veta_darwin_amd64.tar.gz"
      sha256 "b1114808fda44a51d6c94436a5b7bf54a15471e6598274886d009d1bce0fa9cf"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.4/veta_linux_arm64.tar.gz"
      sha256 "242e60141542a24af03af1c831ed68425258a18ffd28da41e6ca143c5e3a8814"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.4/veta_linux_amd64.tar.gz"
      sha256 "dfa95a40170f2709f38a1ebf736def2c433b2b96af5a509e8bdb0cecb0bcafd9"
    end
  end

  def install
    bin.install "veta"
  end

  test do
    system "#{bin}/veta", "--version"
  end
end
