# This file was generated by the Veta release workflow. DO NOT EDIT.
class VetaAT011 < Formula
  desc "Veta static site generator"
  homepage "https://github.com/varavelio/veta"
  license "MIT"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/veta/releases/download/v0.1.1/veta_darwin_arm64.tar.gz"
      sha256 "54223781b82ff42b3b3015ba714024e7c6bffbfe484cde05c5c67cb1745747bb"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.1/veta_darwin_amd64.tar.gz"
      sha256 "5901159eefe3cef6d5d4d5d3e7019dff4585a29535e1e64e46b3a987c89ce87b"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/veta/releases/download/v0.1.1/veta_linux_arm64.tar.gz"
      sha256 "ff906ebe487de2667b8a5fe6b228ae2f3a83d0dcedb0d075c66314613bd376bb"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.1/veta_linux_amd64.tar.gz"
      sha256 "4bcc904ededd635cc2ec91c4394c327aa4ce3e34462da94499cf0df0f98bec5c"
    end
  end

  def install
    bin.install "veta"
  end

  test do
    system "#{bin}/veta", "--version"
  end
end
