# This file was generated by the Veta release workflow. DO NOT EDIT.
class VetaNext < Formula
  desc "Veta static site generator"
  homepage "https://github.com/varavelio/veta"
  license "MIT"
  version "0.1.0-alpha.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.3/veta_darwin_arm64.tar.gz"
      sha256 "04536e8a4592e2ad0cdddb333fd047275bdf5d03c491bbd39e092924e0c3360c"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.3/veta_darwin_amd64.tar.gz"
      sha256 "6f355b1051a4dfef3fdd95253afe5d9ccb4b06501dd00d5f01b1e676646b937b"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.3/veta_linux_arm64.tar.gz"
      sha256 "b2d9044f1adff2d9bd1a5af6afdf635a927a081f209804e64a1deecf6326519b"
    else
      url "https://github.com/varavelio/veta/releases/download/v0.1.0-alpha.3/veta_linux_amd64.tar.gz"
      sha256 "4f36fc382bb2bcd875b906aa2a0dd19307319a5734f6f6d978a241b27c215ec3"
    end
  end

  def install
    bin.install "veta"
  end

  test do
    system "#{bin}/veta", "--version"
  end
end
