# This file was generated by the Zen IdP release workflow. DO NOT EDIT.
class ZenIdp < Formula
  desc "Declarative, zero-maintenance OIDC Identity Provider"
  homepage "https://github.com/varavelio/zen-idp"
  license "MIT"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/zen-idp/releases/download/v0.1.0/zen-idp_darwin_arm64.tar.gz"
      sha256 "4cf2cc373017144289438b4debbe0fe631ecbad604ec8d2093da04fd34b26c00"
    else
      url "https://github.com/varavelio/zen-idp/releases/download/v0.1.0/zen-idp_darwin_amd64.tar.gz"
      sha256 "cc6aeb91a1db2d36e2b18077bb02844eb9688b3fdd0434af75c04459da1006f9"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/zen-idp/releases/download/v0.1.0/zen-idp_linux_arm64.tar.gz"
      sha256 "b349be17341e66e38b34e01ea712443fc31594814a944ff3e39298c6d7c0cfd3"
    else
      url "https://github.com/varavelio/zen-idp/releases/download/v0.1.0/zen-idp_linux_amd64.tar.gz"
      sha256 "fb824cb1c186e7141a115b756ca7ca9a4865672f368e72d275c082a32af84d16"
    end
  end

  def install
    bin.install "zen-idp"
  end

  test do
    system "#{bin}/zen-idp", "help"
  end
end
