# This file was generated by the Zen IdP release workflow. DO NOT EDIT.
class ZenIdpNext < Formula
  desc "Declarative, zero-maintenance OIDC Identity Provider"
  homepage "https://github.com/varavelio/zen-idp"
  license "MIT"
  version "0.1.0-alpha.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/varavelio/zen-idp/releases/download/v0.1.0-alpha.7/zen-idp_darwin_arm64.tar.gz"
      sha256 "35794e822fab3352fdfaf362ba76b3fa19815cfaeddb9bc21f9e44e9cec9bce3"
    else
      url "https://github.com/varavelio/zen-idp/releases/download/v0.1.0-alpha.7/zen-idp_darwin_amd64.tar.gz"
      sha256 "0186af776ec3b5d5744d4639fe63e47d581ba44af0b3b68c9775acaba84cee9c"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varavelio/zen-idp/releases/download/v0.1.0-alpha.7/zen-idp_linux_arm64.tar.gz"
      sha256 "c710df2957b2645f006e8b41638e9fef0a874307dcaafb8bb38f4079abc28be4"
    else
      url "https://github.com/varavelio/zen-idp/releases/download/v0.1.0-alpha.7/zen-idp_linux_amd64.tar.gz"
      sha256 "7716064d798af81b264c9556b29e4cabded99166ef78fb082ef9cd9fb8e765bf"
    end
  end

  def install
    bin.install "zen-idp"
  end

  test do
    system "#{bin}/zen-idp", "help"
  end
end
